# Configuration for the plate assay analysis

assays:
   - "CAT"
   - "SOD"
   - "ACP"
   - "ALP"
   - "AChE"
   - "Bradford"
  
fibers:
  - "Cotton"
  - "PET"

# weeks:
#   - "1-3"
#   - "5-6"

samples:
  - "Gills"
  - "Gland"
  - "Hemolymph"

replicates:
 # - "Rep1"
 # - "Rep2"
 # - "BlankRep"
